// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="canny_edge_detection,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=10.770000,HLS_SYN_LAT=942490,HLS_SYN_TPT=942482,HLS_SYN_MEM=15,HLS_SYN_DSP=5,HLS_SYN_FF=4566,HLS_SYN_LUT=6832}" *)

module canny_edge_detection (
        axis_in_TDATA,
        axis_in_TKEEP,
        axis_in_TSTRB,
        axis_in_TUSER,
        axis_in_TLAST,
        axis_in_TID,
        axis_in_TDEST,
        axis_out_TDATA,
        axis_out_TKEEP,
        axis_out_TSTRB,
        axis_out_TUSER,
        axis_out_TLAST,
        axis_out_TID,
        axis_out_TDEST,
        ap_clk,
        ap_rst_n,
        axis_in_TVALID,
        axis_in_TREADY,
        axis_out_TVALID,
        axis_out_TREADY
);


input  [23:0] axis_in_TDATA;
input  [2:0] axis_in_TKEEP;
input  [2:0] axis_in_TSTRB;
input  [0:0] axis_in_TUSER;
input  [0:0] axis_in_TLAST;
input  [0:0] axis_in_TID;
input  [0:0] axis_in_TDEST;
output  [7:0] axis_out_TDATA;
output  [0:0] axis_out_TKEEP;
output  [0:0] axis_out_TSTRB;
output  [0:0] axis_out_TUSER;
output  [0:0] axis_out_TLAST;
output  [0:0] axis_out_TID;
output  [0:0] axis_out_TDEST;
input   ap_clk;
input   ap_rst_n;
input   axis_in_TVALID;
output   axis_in_TREADY;
output   axis_out_TVALID;
input   axis_out_TREADY;

reg    ap_rst_n_inv;
wire    AXIS2GrayArray_U0_ap_start;
wire    AXIS2GrayArray_U0_ap_done;
wire    AXIS2GrayArray_U0_ap_continue;
wire    AXIS2GrayArray_U0_ap_idle;
wire    AXIS2GrayArray_U0_ap_ready;
wire    AXIS2GrayArray_U0_start_out;
wire    AXIS2GrayArray_U0_start_write;
wire    AXIS2GrayArray_U0_axis_in_TREADY;
wire   [7:0] AXIS2GrayArray_U0_fifo1_din;
wire    AXIS2GrayArray_U0_fifo1_write;
wire    GaussianBlur_U0_ap_start;
wire    GaussianBlur_U0_ap_done;
wire    GaussianBlur_U0_ap_continue;
wire    GaussianBlur_U0_ap_idle;
wire    GaussianBlur_U0_ap_ready;
wire    GaussianBlur_U0_start_out;
wire    GaussianBlur_U0_start_write;
wire    GaussianBlur_U0_fifo1_read;
wire   [7:0] GaussianBlur_U0_fifo2_din;
wire    GaussianBlur_U0_fifo2_write;
wire    Sobel_1280u_720u_U0_ap_start;
wire    Sobel_1280u_720u_U0_ap_done;
wire    Sobel_1280u_720u_U0_ap_continue;
wire    Sobel_1280u_720u_U0_ap_idle;
wire    Sobel_1280u_720u_U0_ap_ready;
wire    Sobel_1280u_720u_U0_start_out;
wire    Sobel_1280u_720u_U0_start_write;
wire    Sobel_1280u_720u_U0_fifo2_read;
wire   [7:0] Sobel_1280u_720u_U0_fifo3_value_din;
wire    Sobel_1280u_720u_U0_fifo3_value_write;
wire   [1:0] Sobel_1280u_720u_U0_fifo3_grad_din;
wire    Sobel_1280u_720u_U0_fifo3_grad_write;
wire    NonMaxSuppression_U0_ap_start;
wire    NonMaxSuppression_U0_ap_done;
wire    NonMaxSuppression_U0_ap_continue;
wire    NonMaxSuppression_U0_ap_idle;
wire    NonMaxSuppression_U0_ap_ready;
wire    NonMaxSuppression_U0_start_out;
wire    NonMaxSuppression_U0_start_write;
wire    NonMaxSuppression_U0_fifo3_value_read;
wire    NonMaxSuppression_U0_fifo3_grad_read;
wire   [7:0] NonMaxSuppression_U0_fifo4_din;
wire    NonMaxSuppression_U0_fifo4_write;
wire    ZeroPadding_U0_ap_start;
wire    ZeroPadding_U0_ap_done;
wire    ZeroPadding_U0_ap_continue;
wire    ZeroPadding_U0_ap_idle;
wire    ZeroPadding_U0_ap_ready;
wire    ZeroPadding_U0_start_out;
wire    ZeroPadding_U0_start_write;
wire    ZeroPadding_U0_fifo4_read;
wire   [7:0] ZeroPadding_U0_fifo5_din;
wire    ZeroPadding_U0_fifo5_write;
wire    HystThreshold_U0_ap_start;
wire    HystThreshold_U0_ap_done;
wire    HystThreshold_U0_ap_continue;
wire    HystThreshold_U0_ap_idle;
wire    HystThreshold_U0_ap_ready;
wire    HystThreshold_U0_start_out;
wire    HystThreshold_U0_start_write;
wire    HystThreshold_U0_fifo5_read;
wire   [7:0] HystThreshold_U0_fifo6_din;
wire    HystThreshold_U0_fifo6_write;
wire    HystThresholdComp_U0_ap_start;
wire    HystThresholdComp_U0_ap_done;
wire    HystThresholdComp_U0_ap_continue;
wire    HystThresholdComp_U0_ap_idle;
wire    HystThresholdComp_U0_ap_ready;
wire    HystThresholdComp_U0_start_out;
wire    HystThresholdComp_U0_start_write;
wire    HystThresholdComp_U0_fifo6_read;
wire   [7:0] HystThresholdComp_U0_fifo7_din;
wire    HystThresholdComp_U0_fifo7_write;
wire    GrayArray2AXIS_U0_ap_start;
wire    GrayArray2AXIS_U0_ap_done;
wire    GrayArray2AXIS_U0_ap_continue;
wire    GrayArray2AXIS_U0_ap_idle;
wire    GrayArray2AXIS_U0_ap_ready;
wire   [7:0] GrayArray2AXIS_U0_axis_out_TDATA;
wire    GrayArray2AXIS_U0_axis_out_TVALID;
wire   [0:0] GrayArray2AXIS_U0_axis_out_TKEEP;
wire   [0:0] GrayArray2AXIS_U0_axis_out_TSTRB;
wire   [0:0] GrayArray2AXIS_U0_axis_out_TUSER;
wire   [0:0] GrayArray2AXIS_U0_axis_out_TLAST;
wire   [0:0] GrayArray2AXIS_U0_axis_out_TID;
wire   [0:0] GrayArray2AXIS_U0_axis_out_TDEST;
wire    GrayArray2AXIS_U0_fifo7_read;
wire    ap_sync_continue;
wire    fifo1_full_n;
wire   [7:0] fifo1_dout;
wire    fifo1_empty_n;
wire    fifo2_full_n;
wire   [7:0] fifo2_dout;
wire    fifo2_empty_n;
wire    fifo3_value_full_n;
wire   [7:0] fifo3_value_dout;
wire    fifo3_value_empty_n;
wire    fifo3_grad_full_n;
wire   [1:0] fifo3_grad_dout;
wire    fifo3_grad_empty_n;
wire    fifo4_full_n;
wire   [7:0] fifo4_dout;
wire    fifo4_empty_n;
wire    fifo5_full_n;
wire   [7:0] fifo5_dout;
wire    fifo5_empty_n;
wire    fifo6_full_n;
wire   [7:0] fifo6_dout;
wire    fifo6_empty_n;
wire    fifo7_full_n;
wire   [7:0] fifo7_dout;
wire    fifo7_empty_n;
wire   [0:0] start_for_GaussianBlur_U0_din;
wire    start_for_GaussianBlur_U0_full_n;
wire   [0:0] start_for_GaussianBlur_U0_dout;
wire    start_for_GaussianBlur_U0_empty_n;
wire   [0:0] start_for_Sobel_1280u_720u_U0_din;
wire    start_for_Sobel_1280u_720u_U0_full_n;
wire   [0:0] start_for_Sobel_1280u_720u_U0_dout;
wire    start_for_Sobel_1280u_720u_U0_empty_n;
wire   [0:0] start_for_NonMaxSuppression_U0_din;
wire    start_for_NonMaxSuppression_U0_full_n;
wire   [0:0] start_for_NonMaxSuppression_U0_dout;
wire    start_for_NonMaxSuppression_U0_empty_n;
wire   [0:0] start_for_ZeroPadding_U0_din;
wire    start_for_ZeroPadding_U0_full_n;
wire   [0:0] start_for_ZeroPadding_U0_dout;
wire    start_for_ZeroPadding_U0_empty_n;
wire   [0:0] start_for_HystThreshold_U0_din;
wire    start_for_HystThreshold_U0_full_n;
wire   [0:0] start_for_HystThreshold_U0_dout;
wire    start_for_HystThreshold_U0_empty_n;
wire   [0:0] start_for_HystThresholdComp_U0_din;
wire    start_for_HystThresholdComp_U0_full_n;
wire   [0:0] start_for_HystThresholdComp_U0_dout;
wire    start_for_HystThresholdComp_U0_empty_n;
wire   [0:0] start_for_GrayArray2AXIS_U0_din;
wire    start_for_GrayArray2AXIS_U0_full_n;
wire   [0:0] start_for_GrayArray2AXIS_U0_dout;
wire    start_for_GrayArray2AXIS_U0_empty_n;
wire    GrayArray2AXIS_U0_start_full_n;
wire    GrayArray2AXIS_U0_start_write;

AXIS2GrayArray AXIS2GrayArray_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIS2GrayArray_U0_ap_start),
    .start_full_n(start_for_GaussianBlur_U0_full_n),
    .ap_done(AXIS2GrayArray_U0_ap_done),
    .ap_continue(AXIS2GrayArray_U0_ap_continue),
    .ap_idle(AXIS2GrayArray_U0_ap_idle),
    .ap_ready(AXIS2GrayArray_U0_ap_ready),
    .start_out(AXIS2GrayArray_U0_start_out),
    .start_write(AXIS2GrayArray_U0_start_write),
    .axis_in_TDATA(axis_in_TDATA),
    .axis_in_TVALID(axis_in_TVALID),
    .axis_in_TREADY(AXIS2GrayArray_U0_axis_in_TREADY),
    .axis_in_TKEEP(axis_in_TKEEP),
    .axis_in_TSTRB(axis_in_TSTRB),
    .axis_in_TUSER(axis_in_TUSER),
    .axis_in_TLAST(axis_in_TLAST),
    .axis_in_TID(axis_in_TID),
    .axis_in_TDEST(axis_in_TDEST),
    .fifo1_din(AXIS2GrayArray_U0_fifo1_din),
    .fifo1_full_n(fifo1_full_n),
    .fifo1_write(AXIS2GrayArray_U0_fifo1_write)
);

GaussianBlur GaussianBlur_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(GaussianBlur_U0_ap_start),
    .start_full_n(start_for_Sobel_1280u_720u_U0_full_n),
    .ap_done(GaussianBlur_U0_ap_done),
    .ap_continue(GaussianBlur_U0_ap_continue),
    .ap_idle(GaussianBlur_U0_ap_idle),
    .ap_ready(GaussianBlur_U0_ap_ready),
    .start_out(GaussianBlur_U0_start_out),
    .start_write(GaussianBlur_U0_start_write),
    .fifo1_dout(fifo1_dout),
    .fifo1_empty_n(fifo1_empty_n),
    .fifo1_read(GaussianBlur_U0_fifo1_read),
    .fifo2_din(GaussianBlur_U0_fifo2_din),
    .fifo2_full_n(fifo2_full_n),
    .fifo2_write(GaussianBlur_U0_fifo2_write)
);

Sobel_1280u_720u_s Sobel_1280u_720u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Sobel_1280u_720u_U0_ap_start),
    .start_full_n(start_for_NonMaxSuppression_U0_full_n),
    .ap_done(Sobel_1280u_720u_U0_ap_done),
    .ap_continue(Sobel_1280u_720u_U0_ap_continue),
    .ap_idle(Sobel_1280u_720u_U0_ap_idle),
    .ap_ready(Sobel_1280u_720u_U0_ap_ready),
    .start_out(Sobel_1280u_720u_U0_start_out),
    .start_write(Sobel_1280u_720u_U0_start_write),
    .fifo2_dout(fifo2_dout),
    .fifo2_empty_n(fifo2_empty_n),
    .fifo2_read(Sobel_1280u_720u_U0_fifo2_read),
    .fifo3_value_din(Sobel_1280u_720u_U0_fifo3_value_din),
    .fifo3_value_full_n(fifo3_value_full_n),
    .fifo3_value_write(Sobel_1280u_720u_U0_fifo3_value_write),
    .fifo3_grad_din(Sobel_1280u_720u_U0_fifo3_grad_din),
    .fifo3_grad_full_n(fifo3_grad_full_n),
    .fifo3_grad_write(Sobel_1280u_720u_U0_fifo3_grad_write)
);

NonMaxSuppression NonMaxSuppression_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(NonMaxSuppression_U0_ap_start),
    .start_full_n(start_for_ZeroPadding_U0_full_n),
    .ap_done(NonMaxSuppression_U0_ap_done),
    .ap_continue(NonMaxSuppression_U0_ap_continue),
    .ap_idle(NonMaxSuppression_U0_ap_idle),
    .ap_ready(NonMaxSuppression_U0_ap_ready),
    .start_out(NonMaxSuppression_U0_start_out),
    .start_write(NonMaxSuppression_U0_start_write),
    .fifo3_value_dout(fifo3_value_dout),
    .fifo3_value_empty_n(fifo3_value_empty_n),
    .fifo3_value_read(NonMaxSuppression_U0_fifo3_value_read),
    .fifo3_grad_dout(fifo3_grad_dout),
    .fifo3_grad_empty_n(fifo3_grad_empty_n),
    .fifo3_grad_read(NonMaxSuppression_U0_fifo3_grad_read),
    .fifo4_din(NonMaxSuppression_U0_fifo4_din),
    .fifo4_full_n(fifo4_full_n),
    .fifo4_write(NonMaxSuppression_U0_fifo4_write)
);

ZeroPadding ZeroPadding_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ZeroPadding_U0_ap_start),
    .start_full_n(start_for_HystThreshold_U0_full_n),
    .ap_done(ZeroPadding_U0_ap_done),
    .ap_continue(ZeroPadding_U0_ap_continue),
    .ap_idle(ZeroPadding_U0_ap_idle),
    .ap_ready(ZeroPadding_U0_ap_ready),
    .start_out(ZeroPadding_U0_start_out),
    .start_write(ZeroPadding_U0_start_write),
    .fifo4_dout(fifo4_dout),
    .fifo4_empty_n(fifo4_empty_n),
    .fifo4_read(ZeroPadding_U0_fifo4_read),
    .fifo5_din(ZeroPadding_U0_fifo5_din),
    .fifo5_full_n(fifo5_full_n),
    .fifo5_write(ZeroPadding_U0_fifo5_write)
);

HystThreshold HystThreshold_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(HystThreshold_U0_ap_start),
    .start_full_n(start_for_HystThresholdComp_U0_full_n),
    .ap_done(HystThreshold_U0_ap_done),
    .ap_continue(HystThreshold_U0_ap_continue),
    .ap_idle(HystThreshold_U0_ap_idle),
    .ap_ready(HystThreshold_U0_ap_ready),
    .start_out(HystThreshold_U0_start_out),
    .start_write(HystThreshold_U0_start_write),
    .fifo5_dout(fifo5_dout),
    .fifo5_empty_n(fifo5_empty_n),
    .fifo5_read(HystThreshold_U0_fifo5_read),
    .fifo6_din(HystThreshold_U0_fifo6_din),
    .fifo6_full_n(fifo6_full_n),
    .fifo6_write(HystThreshold_U0_fifo6_write)
);

HystThresholdComp HystThresholdComp_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(HystThresholdComp_U0_ap_start),
    .start_full_n(start_for_GrayArray2AXIS_U0_full_n),
    .ap_done(HystThresholdComp_U0_ap_done),
    .ap_continue(HystThresholdComp_U0_ap_continue),
    .ap_idle(HystThresholdComp_U0_ap_idle),
    .ap_ready(HystThresholdComp_U0_ap_ready),
    .start_out(HystThresholdComp_U0_start_out),
    .start_write(HystThresholdComp_U0_start_write),
    .fifo6_dout(fifo6_dout),
    .fifo6_empty_n(fifo6_empty_n),
    .fifo6_read(HystThresholdComp_U0_fifo6_read),
    .fifo7_din(HystThresholdComp_U0_fifo7_din),
    .fifo7_full_n(fifo7_full_n),
    .fifo7_write(HystThresholdComp_U0_fifo7_write)
);

GrayArray2AXIS GrayArray2AXIS_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(GrayArray2AXIS_U0_ap_start),
    .ap_done(GrayArray2AXIS_U0_ap_done),
    .ap_continue(GrayArray2AXIS_U0_ap_continue),
    .ap_idle(GrayArray2AXIS_U0_ap_idle),
    .ap_ready(GrayArray2AXIS_U0_ap_ready),
    .axis_out_TDATA(GrayArray2AXIS_U0_axis_out_TDATA),
    .axis_out_TVALID(GrayArray2AXIS_U0_axis_out_TVALID),
    .axis_out_TREADY(axis_out_TREADY),
    .axis_out_TKEEP(GrayArray2AXIS_U0_axis_out_TKEEP),
    .axis_out_TSTRB(GrayArray2AXIS_U0_axis_out_TSTRB),
    .axis_out_TUSER(GrayArray2AXIS_U0_axis_out_TUSER),
    .axis_out_TLAST(GrayArray2AXIS_U0_axis_out_TLAST),
    .axis_out_TID(GrayArray2AXIS_U0_axis_out_TID),
    .axis_out_TDEST(GrayArray2AXIS_U0_axis_out_TDEST),
    .fifo7_dout(fifo7_dout),
    .fifo7_empty_n(fifo7_empty_n),
    .fifo7_read(GrayArray2AXIS_U0_fifo7_read)
);

fifo_w8_d1_A fifo1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIS2GrayArray_U0_fifo1_din),
    .if_full_n(fifo1_full_n),
    .if_write(AXIS2GrayArray_U0_fifo1_write),
    .if_dout(fifo1_dout),
    .if_empty_n(fifo1_empty_n),
    .if_read(GaussianBlur_U0_fifo1_read)
);

fifo_w8_d1_A fifo2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(GaussianBlur_U0_fifo2_din),
    .if_full_n(fifo2_full_n),
    .if_write(GaussianBlur_U0_fifo2_write),
    .if_dout(fifo2_dout),
    .if_empty_n(fifo2_empty_n),
    .if_read(Sobel_1280u_720u_U0_fifo2_read)
);

fifo_w8_d1_A fifo3_value_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_1280u_720u_U0_fifo3_value_din),
    .if_full_n(fifo3_value_full_n),
    .if_write(Sobel_1280u_720u_U0_fifo3_value_write),
    .if_dout(fifo3_value_dout),
    .if_empty_n(fifo3_value_empty_n),
    .if_read(NonMaxSuppression_U0_fifo3_value_read)
);

fifo_w2_d1_A fifo3_grad_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_1280u_720u_U0_fifo3_grad_din),
    .if_full_n(fifo3_grad_full_n),
    .if_write(Sobel_1280u_720u_U0_fifo3_grad_write),
    .if_dout(fifo3_grad_dout),
    .if_empty_n(fifo3_grad_empty_n),
    .if_read(NonMaxSuppression_U0_fifo3_grad_read)
);

fifo_w8_d1_A fifo4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(NonMaxSuppression_U0_fifo4_din),
    .if_full_n(fifo4_full_n),
    .if_write(NonMaxSuppression_U0_fifo4_write),
    .if_dout(fifo4_dout),
    .if_empty_n(fifo4_empty_n),
    .if_read(ZeroPadding_U0_fifo4_read)
);

fifo_w8_d1_A fifo5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(ZeroPadding_U0_fifo5_din),
    .if_full_n(fifo5_full_n),
    .if_write(ZeroPadding_U0_fifo5_write),
    .if_dout(fifo5_dout),
    .if_empty_n(fifo5_empty_n),
    .if_read(HystThreshold_U0_fifo5_read)
);

fifo_w8_d1_A fifo6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HystThreshold_U0_fifo6_din),
    .if_full_n(fifo6_full_n),
    .if_write(HystThreshold_U0_fifo6_write),
    .if_dout(fifo6_dout),
    .if_empty_n(fifo6_empty_n),
    .if_read(HystThresholdComp_U0_fifo6_read)
);

fifo_w8_d1_A fifo7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(HystThresholdComp_U0_fifo7_din),
    .if_full_n(fifo7_full_n),
    .if_write(HystThresholdComp_U0_fifo7_write),
    .if_dout(fifo7_dout),
    .if_empty_n(fifo7_empty_n),
    .if_read(GrayArray2AXIS_U0_fifo7_read)
);

start_for_Gaussiaocq start_for_Gaussiaocq_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_GaussianBlur_U0_din),
    .if_full_n(start_for_GaussianBlur_U0_full_n),
    .if_write(AXIS2GrayArray_U0_start_write),
    .if_dout(start_for_GaussianBlur_U0_dout),
    .if_empty_n(start_for_GaussianBlur_U0_empty_n),
    .if_read(GaussianBlur_U0_ap_ready)
);

start_for_Sobel_1pcA start_for_Sobel_1pcA_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Sobel_1280u_720u_U0_din),
    .if_full_n(start_for_Sobel_1280u_720u_U0_full_n),
    .if_write(GaussianBlur_U0_start_write),
    .if_dout(start_for_Sobel_1280u_720u_U0_dout),
    .if_empty_n(start_for_Sobel_1280u_720u_U0_empty_n),
    .if_read(Sobel_1280u_720u_U0_ap_ready)
);

start_for_NonMaxSqcK start_for_NonMaxSqcK_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_NonMaxSuppression_U0_din),
    .if_full_n(start_for_NonMaxSuppression_U0_full_n),
    .if_write(Sobel_1280u_720u_U0_start_write),
    .if_dout(start_for_NonMaxSuppression_U0_dout),
    .if_empty_n(start_for_NonMaxSuppression_U0_empty_n),
    .if_read(NonMaxSuppression_U0_ap_ready)
);

start_for_ZeroPadrcU start_for_ZeroPadrcU_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_ZeroPadding_U0_din),
    .if_full_n(start_for_ZeroPadding_U0_full_n),
    .if_write(NonMaxSuppression_U0_start_write),
    .if_dout(start_for_ZeroPadding_U0_dout),
    .if_empty_n(start_for_ZeroPadding_U0_empty_n),
    .if_read(ZeroPadding_U0_ap_ready)
);

start_for_HystThrsc4 start_for_HystThrsc4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_HystThreshold_U0_din),
    .if_full_n(start_for_HystThreshold_U0_full_n),
    .if_write(ZeroPadding_U0_start_write),
    .if_dout(start_for_HystThreshold_U0_dout),
    .if_empty_n(start_for_HystThreshold_U0_empty_n),
    .if_read(HystThreshold_U0_ap_ready)
);

start_for_HystThrtde start_for_HystThrtde_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_HystThresholdComp_U0_din),
    .if_full_n(start_for_HystThresholdComp_U0_full_n),
    .if_write(HystThreshold_U0_start_write),
    .if_dout(start_for_HystThresholdComp_U0_dout),
    .if_empty_n(start_for_HystThresholdComp_U0_empty_n),
    .if_read(HystThresholdComp_U0_ap_ready)
);

start_for_GrayArrudo start_for_GrayArrudo_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_GrayArray2AXIS_U0_din),
    .if_full_n(start_for_GrayArray2AXIS_U0_full_n),
    .if_write(HystThresholdComp_U0_start_write),
    .if_dout(start_for_GrayArray2AXIS_U0_dout),
    .if_empty_n(start_for_GrayArray2AXIS_U0_empty_n),
    .if_read(GrayArray2AXIS_U0_ap_ready)
);

assign AXIS2GrayArray_U0_ap_continue = 1'b1;

assign AXIS2GrayArray_U0_ap_start = 1'b1;

assign GaussianBlur_U0_ap_continue = 1'b1;

assign GaussianBlur_U0_ap_start = start_for_GaussianBlur_U0_empty_n;

assign GrayArray2AXIS_U0_ap_continue = 1'b1;

assign GrayArray2AXIS_U0_ap_start = start_for_GrayArray2AXIS_U0_empty_n;

assign GrayArray2AXIS_U0_start_full_n = 1'b1;

assign GrayArray2AXIS_U0_start_write = 1'b0;

assign HystThresholdComp_U0_ap_continue = 1'b1;

assign HystThresholdComp_U0_ap_start = start_for_HystThresholdComp_U0_empty_n;

assign HystThreshold_U0_ap_continue = 1'b1;

assign HystThreshold_U0_ap_start = start_for_HystThreshold_U0_empty_n;

assign NonMaxSuppression_U0_ap_continue = 1'b1;

assign NonMaxSuppression_U0_ap_start = start_for_NonMaxSuppression_U0_empty_n;

assign Sobel_1280u_720u_U0_ap_continue = 1'b1;

assign Sobel_1280u_720u_U0_ap_start = start_for_Sobel_1280u_720u_U0_empty_n;

assign ZeroPadding_U0_ap_continue = 1'b1;

assign ZeroPadding_U0_ap_start = start_for_ZeroPadding_U0_empty_n;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign axis_in_TREADY = AXIS2GrayArray_U0_axis_in_TREADY;

assign axis_out_TDATA = GrayArray2AXIS_U0_axis_out_TDATA;

assign axis_out_TDEST = GrayArray2AXIS_U0_axis_out_TDEST;

assign axis_out_TID = GrayArray2AXIS_U0_axis_out_TID;

assign axis_out_TKEEP = GrayArray2AXIS_U0_axis_out_TKEEP;

assign axis_out_TLAST = GrayArray2AXIS_U0_axis_out_TLAST;

assign axis_out_TSTRB = GrayArray2AXIS_U0_axis_out_TSTRB;

assign axis_out_TUSER = GrayArray2AXIS_U0_axis_out_TUSER;

assign axis_out_TVALID = GrayArray2AXIS_U0_axis_out_TVALID;

assign start_for_GaussianBlur_U0_din = 1'b1;

assign start_for_GrayArray2AXIS_U0_din = 1'b1;

assign start_for_HystThresholdComp_U0_din = 1'b1;

assign start_for_HystThreshold_U0_din = 1'b1;

assign start_for_NonMaxSuppression_U0_din = 1'b1;

assign start_for_Sobel_1280u_720u_U0_din = 1'b1;

assign start_for_ZeroPadding_U0_din = 1'b1;

endmodule //canny_edge_detection
