webtalk_init -webtalk_dir /home/catabit/Zybo/SDCar/SDCarVivado/SDCarVivado.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-04-19 18:23:41" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "q7dj2arqppqpvd3u1fl993gepc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2635.664 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.214 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1555686713000" -context "sdk\\\\application/1555686713000"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1555686713000"
webtalk_add_data -client sdk -key apptemplate -value "linux_empty_app" -context "sdk\\\\application/1555686713000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1555686713000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1555686713000"
webtalk_add_data -client sdk -key Procused -value "" -context "sdk\\\\application/1555686713000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1555687421871"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1555687421871"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1555687421871"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1555687421871"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1555687421871"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1555687421871"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1555687421871"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1555687421871"
webtalk_transmit -clientid 250242791 -regid "" -xml /home/catabit/Zybo/SDCar/SDCarVivado/SDCarVivado.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/catabit/Zybo/SDCar/SDCarVivado/SDCarVivado.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/catabit/Zybo/SDCar/SDCarVivado/SDCarVivado.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
